# Generated by Django 4.1.2 on 2022-11-01 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='modified_at', null=True)),
                ('created_by', models.CharField(blank=True, db_column='created_by', default='', max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, db_column='modified_by', default='', max_length=100, null=True)),
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('full_name', models.CharField(db_column='full_name', max_length=100)),
                ('user_name', models.CharField(db_column='user_name', max_length=100)),
                ('password', models.CharField(db_column='password', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
